# Generated by Django 5.0.1 on 2024-03-20 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('campo', models.CharField(blank=True, max_length=150)),
                ('monto', models.FloatField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil')),
            ],
        ),
    ]
