# Generated by Django 5.0.1 on 2024-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='monto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
