# Generated by Django 5.0.1 on 2024-03-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='identificador',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
