# Generated by Django 5.0.1 on 2024-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_servicio_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='identificador',
            field=models.CharField(max_length=20),
        ),
    ]
