# Generated by Django 5.0.1 on 2024-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='beneficiario',
            new_name='informacion',
        ),
    ]
