# Generated by Django 5.0.1 on 2024-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
