# Generated by Django 5.0.1 on 2024-02-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('no_cuenta', models.TextField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('saldo', models.FloatField()),
                ('limite_ATM', models.IntegerField()),
                ('limite_POS', models.IntegerField()),
                ('tipo_cuenta', models.TextField(max_length=3)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil')),
            ],
        ),
    ]
